`timescale 1ns/1ps
//=============================================================================
// tb_fp32_add -- standalone regression for the FP32 adder.
//
// WHY THIS EXISTS SEPARATELY, and why it runs before tb_amx_fp8. amx_fp8
// instantiates this block 1024 times inside a 16-cycle accumulation. A rounding
// bug found there presents as "some matrix elements are off by an ulp", which is
// indistinguishable from a schedule bug, a format-decode bug, or a lane-mapping
// bug. Found here it presents as "vector 41 wants 3F800002, got 3F800001".
//
//------------------------------------------------- THE MODEL IS NOT THE DUT
// ref_add() below computes the EXACT sum in a 320-bit fixed-point register and
// rounds ONCE. That is the definition of IEEE addition. The DUT does something
// structurally different: it caps its alignment shifter at 27 positions, folds
// everything past that into a sticky bit, counts leading zeros with a 5-level
// binary search, and renormalises. So the model does not share the DUT's
// approximations, which is the whole point -- the shift cap, the sticky OR and
// the LZC are exactly what these vectors are here to validate.
//
// WHAT THE MODEL ALONE WOULD NOT PROVE: that it is itself right. So the 24
// directed vec() lines carry expected values generated by tb/fp8_golden.py,
// where two further independent models agree (exact-integer, and the C
// library's FP64 adder rounded to FP32 -- sound for a single add because
// 53 >= 2*24+2). vec() checks the DUT *and* ref_add against those constants, so
// ref_add is validated before the random sweep leans on it.
//
//------------------------------------------------------------ WHAT IS COVERED
//   RNE ties            both parities, at 1+2^-24 and at the 2^24 integer cliff
//   the shift cap       exponent differences 0..40, straddling the cap at 27
//   cancellation        operands differing by 1..8 ulp, the deep-LZC path
//   DAZ                 subnormal inputs must behave as zero
//   FTZ                 a subnormal result must flush to a signed zero
//   signed zeros        (-0)+(-0) = -0, (-0)+(+0) = +0, exact cancel = +0
//   Inf/NaN             including (+Inf)+(-Inf) = NaN and Inf x 0 upstream
//   commutativity       a+b must equal b+a for every vector, which is what
//                       catches a broken magnitude swap
//=============================================================================
module tb_fp32_add;

    // parameter, not localparam, so a deep run can be asked for from the
    // command line: -Ptb_fp32_add.NRAND=500000
    parameter integer NRAND = 20000;

    reg  [31:0] a_in, b_in;
    wire [31:0] y_out;

    fp32_add dut (.a(a_in), .b(b_in), .y(y_out));

    integer pass_count = 0;
    integer fail_count = 0;
    integer shown      = 0;
    integer seed;

    // ---- the reference: exact sum, one rounding ---------------------------
    // 320 bits because two normals can be 254 binades apart and the exact sum
    // then needs 24+254 = 278 bits. NOTHING here is bounded or capped; that is
    // the difference from the DUT.
    function [31:0] ref_add;
        input [31:0] a;
        input [31:0] b;
        reg         sa, sb;
        reg  [7:0]  ea, eb;
        reg  [22:0] fa, fb;
        reg  [23:0] ma, mb;
        integer     ka, kb, kmin, nb, drop, expv, ef;
        reg  [319:0] pa, pb, mag, m24, lowmask;
        reg         rbit, sticky, sgn;
        begin
            sa = a[31]; ea = a[30:23]; fa = a[22:0];
            sb = b[31]; eb = b[30:23]; fb = b[22:0];
            if ((ea == 8'hFF && fa != 0) || (eb == 8'hFF && fb != 0))
                ref_add = 32'h7FC0_0000;                       // NaN in
            else if (ea == 8'hFF && eb == 8'hFF)
                ref_add = (sa != sb) ? 32'h7FC0_0000 : a;      // Inf +- Inf
            else if (ea == 8'hFF) ref_add = a;
            else if (eb == 8'hFF) ref_add = b;
            else begin
                ma = (ea == 8'd0) ? 24'd0 : {1'b1, fa};        // DAZ
                mb = (eb == 8'd0) ? 24'd0 : {1'b1, fb};
                if (ma == 24'd0 && mb == 24'd0)
                    // signed zeros: -0 only when both were -0
                    ref_add = (sa && sb) ? 32'h8000_0000 : 32'h0000_0000;
                else begin
                    ka   = (ea == 8'd0) ? -150 : (ea - 150);
                    kb   = (eb == 8'd0) ? -150 : (eb - 150);
                    kmin = (ka < kb) ? ka : kb;
                    pa   = {296'd0, ma} << (ka - kmin);
                    pb   = {296'd0, mb} << (kb - kmin);
                    if (sa == sb)      begin sgn = sa; mag = pa + pb; end
                    else if (pa >= pb) begin sgn = sa; mag = pa - pb; end
                    else               begin sgn = sb; mag = pb - pa; end
                    if (mag == 320'd0)
                        ref_add = 32'h0000_0000;    // exact cancel is +0 in RNE
                    else begin
                        nb = 320;
                        while (nb > 0 && !mag[nb-1]) nb = nb - 1;
                        expv = kmin + nb - 1;
                        drop = nb - 24;
                        if (drop <= 0) begin
                            m24 = mag << (-drop); rbit = 1'b0; sticky = 1'b0;
                        end else begin
                            m24     = mag >> drop;
                            rbit    = mag[drop-1];
                            lowmask = ~({320{1'b1}} << (drop - 1));
                            sticky  = |(mag & lowmask);
                        end
                        if (rbit && (sticky || m24[0])) begin
                            m24 = m24 + 320'd1;
                            if (m24[24]) begin
                                m24  = m24 >> 1;
                                expv = expv + 1;
                            end
                        end
                        ef = expv + 127;
                        if      (ef >= 255) ref_add = {sgn, 8'hFF, 23'd0};
                        else if (ef <= 0)   ref_add = {sgn, 31'd0};   // FTZ
                        else                ref_add = {sgn, ef[7:0], m24[22:0]};
                    end
                end
            end
        end
    endfunction

    // ---- checkers ----------------------------------------------------------
    // COMMUTATIVITY IS CHECKED ON EVERY VECTOR. The DUT decides which operand is
    // "big" with a single 31-bit compare; getting that backwards is correct for
    // half of all inputs, and a+b != b+a is the cheapest way to catch it.
    task expect_eq(input [31:0] a, input [31:0] b, input [31:0] want,
                   input [8*20:1] tag);
        reg [31:0] fwd, rev;
        begin
            a_in = a; b_in = b; #1; fwd = y_out;
            a_in = b; b_in = a; #1; rev = y_out;
            if (fwd !== want || rev !== want) begin
                fail_count = fail_count + 1;
                if (shown < 20) begin
                    shown = shown + 1;
                    $display("  [FAIL] %0s  %08h + %08h : got %08h rev %08h want %08h",
                             tag, a, b, fwd, rev, want);
                end
            end else pass_count = pass_count + 1;
        end
    endtask

    // Directed vector with a constant from tb/fp8_golden.py. Checks the DUT AND
    // the local model, so ref_add is validated before the sweeps rely on it.
    task vec(input [31:0] a, input [31:0] b, input [31:0] want);
        begin
            expect_eq(a, b, want, "directed");
            if (ref_add(a, b) !== want) begin
                fail_count = fail_count + 1;
                $display("  [FAIL] ref_add DISAGREES WITH PYTHON %08h + %08h : model %08h want %08h",
                         a, b, ref_add(a, b), want);
            end
        end
    endtask

    // Bulk check against the local model.
    task chk(input [31:0] a, input [31:0] b);
        begin
            expect_eq(a, b, ref_add(a, b), "vs ref_add");
        end
    endtask

    // Loop counters are integers; anything that gets CONCATENATED into a 32-bit
    // float pattern needs a width-typed reg, because an integer cannot be
    // part-selected in Verilog-2001 and an unsized expression in a
    // concatenation has no defined width.
    integer d, i, j, e, grp, fsel;
    reg [7:0]  et, et2;
    reg [22:0] ft, ft2;
    reg        st, st2;
    reg [31:0] x, yv;

    initial begin
        seed = 32'h5EED_F00D;
        $display("=== tb_fp32_add  (NRAND=%0d) ===", NRAND);

        // ---- 1. directed, cross-language tie -------------------------------
        // generated: python3 tb/fp8_golden.py  (both python models agree on every line)
        vec(32'h3F800000, 32'h3F800000, 32'h40000000);   // 1+1
        vec(32'h3F800000, 32'hBF800000, 32'h00000000);   // 1+(-1) exact cancel -> +0
        vec(32'h3F800000, 32'h33800000, 32'h3F800000);   // 1 + 2^-24  tie, lsb even -> truncate
        vec(32'h3F800001, 32'h33800000, 32'h3F800002);   // 1+ulp + 2^-24  tie, lsb odd -> round up
        vec(32'h3F800000, 32'h33000000, 32'h3F800000);   // 1 + 2^-25  below half -> truncate
        vec(32'h3F800000, 32'h34000000, 32'h3F800001);   // 1 + 2^-23  exact ulp
        vec(32'h4B000000, 32'h3F800000, 32'h4B000001);   // 2^23 + 1  last exact integer step
        vec(32'h4B800000, 32'h3F800000, 32'h4B800000);   // 2^24 + 1  tie at the integer cliff
        vec(32'h4B800001, 32'h3F800000, 32'h4B800002);   // 2^24+ulp + 1
        vec(32'h3F800000, 32'h00000001, 32'h3F800000);   // 1 + smallest subnormal (DAZ -> 1)
        vec(32'h00000001, 32'h80000001, 32'h00000000);   // subnormal + -subnormal (both DAZ zero)
        vec(32'h80000000, 32'h80000000, 32'h80000000);   // (-0)+(-0) -> -0
        vec(32'h80000000, 32'h00000000, 32'h00000000);   // (-0)+(+0) -> +0
        vec(32'h7F7FFFFF, 32'h7F7FFFFF, 32'h7F800000);   // max+max -> overflow to Inf
        vec(32'h7F7FFFFF, 32'h70000000, 32'h7F7FFFFF);   // max + small, no overflow
        vec(32'h40000000, 32'hBFFFFFFF, 32'h34000000);   // 2 + (-(2-ulp)) massive cancellation
        vec(32'h3F800000, 32'hBF7FFFFF, 32'h33800000);   // 1 + (-(1-ulp)) cancellation to 2^-24
        vec(32'h7F800000, 32'hFF800000, 32'h7FC00000);   // (+Inf)+(-Inf) -> NaN
        vec(32'h7F800000, 32'h3F800000, 32'h7F800000);   // Inf + 1 -> Inf
        vec(32'h7FC00000, 32'h3F800000, 32'h7FC00000);   // NaN + 1 -> NaN
        vec(32'h00800000, 32'h80800001, 32'h80000000);   // min normal + -(min normal+ulp)  FTZ path
        vec(32'h4C000000, 32'h3F800000, 32'h4C000000);   // 2^25 + 1  d=25, inside the shift cap
        vec(32'h4D000000, 32'h3F800000, 32'h4D000000);   // 2^27 + 1  d=27, AT the shift cap
        vec(32'h4E000000, 32'h3F800000, 32'h4E000000);   // 2^29 + 1  d=29, past the cap -> sticky only
        $display("  24 directed vectors done (%0d fail so far)", fail_count);

        // ---- 2. the shift cap, swept ---------------------------------------
        // The DUT caps its aligner at 27 and turns everything beyond into
        // sticky. d = 24..30 is where a cap off by one shows up, so sweep
        // straight through it with fractions that make the sticky bit matter.
        for (d = 0; d <= 40; d = d + 1)
            for (fsel = 0; fsel < 6; fsel = fsel + 1)
                for (j = 0; j < 2; j = j + 1) begin
                    case (fsel)
                        0: ft = 23'h000000;
                        1: ft = 23'h000001;
                        2: ft = 23'h400000;
                        3: ft = 23'h7FFFFF;
                        4: ft = 23'h555555;
                        default: ft = 23'h2AAAAA;
                    endcase
                    et = 8'd127 + d;
                    st = (j != 0);
                    chk({1'b0, et, 23'h000000}, {st, 8'd127, ft});
                    chk({1'b0, et, ft},         {st, 8'd127, 23'h7FFFFF});
                end
        $display("  shift-cap sweep d=0..40 done (%0d fail so far)", fail_count);

        // ---- 3. cancellation: the deep leading-zero path -------------------
        // Operands within a few ulp of each other cancel down to a handful of
        // significant bits, which is the only thing that exercises a 27-deep
        // normalise. An LZC that saturates early survives everything else.
        for (e = 100; e <= 160; e = e + 12)
            for (i = 1; i <= 8; i = i + 1) begin
                et  = e;
                et2 = e - 1;
                ft  = i;
                chk({1'b0, et, 23'h400000}, {1'b1, et, (23'h400000 - ft)});
                chk({1'b0, et, 23'h7FFFFF}, {1'b1, et, (23'h7FFFFF - ft)});
                // one binade apart, so the subtract borrows across the exponent
                chk({1'b0, et, 23'h000000}, {1'b1, et2, (23'h7FFFFF - ft)});
            end
        $display("  cancellation sweep done (%0d fail so far)", fail_count);

        // ---- 4. DAZ and FTZ ------------------------------------------------
        // Every subnormal input must read as zero, and a result that lands
        // below the min normal must flush. Both are ISA behaviour here, not
        // IEEE default, so neither is inherited from anywhere.
        for (i = 0; i < 23; i = i + 1) begin
            ft = 23'd1 << i;
            chk({1'b0, 8'd0, ft}, 32'h3F800000);      // subnormal + 1
            chk({1'b1, 8'd0, ft}, 32'h00000000);      // -subnormal + 0
            chk({1'b0, 8'd0, ft}, {1'b0, 8'd0, 23'h000001});
        end
        // results just below the min normal: min_normal - k*ulp is subnormal
        for (i = 1; i <= 16; i = i + 1) begin
            ft = i;
            chk(32'h00800000, {1'b1, 8'd0, ft});
        end
        for (i = 0; i < 8; i = i + 1) begin
            ft  = i;
            ft2 = i + 1;
            chk({1'b0, 8'd1, ft}, {1'b1, 8'd1, ft2});
        end

        // THE FTZ BOUNDARY ITSELF. Everything above lands far below the min
        // normal, where flushing at exponent <= 0 and flushing at exponent < 0
        // give the same answer -- so a threshold off by one survived all of it.
        // These land the RESULT exactly on e_fin = 0, 1 and 2, which is the only
        // place the two differ: at e_fin = 0 the value is subnormal and must
        // flush; at e_fin = 1 it is the min normal and must NOT.
        chk({1'b0, 8'd1, 23'h400000}, {1'b1, 8'd1, 23'h000000});  // 2^-127, e=0, flush
        chk({1'b1, 8'd1, 23'h400000}, {1'b0, 8'd1, 23'h000000});  // -2^-127 -> -0
        chk({1'b0, 8'd2, 23'h000000}, {1'b1, 8'd1, 23'h400000});  // 2^-127, e=0, flush
        chk({1'b0, 8'd2, 23'h000000}, {1'b1, 8'd1, 23'h000000});  // 2^-126, e=1, KEEP
        chk({1'b0, 8'd1, 23'h000000}, {1'b0, 8'd1, 23'h000000});  // 2^-125, e=2, KEEP
        chk({1'b0, 8'd1, 23'h000001}, {1'b1, 8'd1, 23'h000000});  // 1 ulp, deep flush
        chk({1'b0, 8'd3, 23'h000000}, {1'b1, 8'd2, 23'h400000});  // 2^-126, e=1, KEEP
        for (i = 0; i < 8; i = i + 1) begin
            ft = 23'h400000 + i;
            chk({1'b0, 8'd1, ft}, {1'b1, 8'd1, 23'h000000});      // straddle e=0
            chk({1'b0, 8'd2, ft}, {1'b1, 8'd1, 23'h000000});      // straddle e=1
        end
        $display("  DAZ/FTZ sweep done (%0d fail so far)", fail_count);

        // ---- 5. specials, every pairing ------------------------------------
        for (i = 0; i < 6; i = i + 1)
            for (j = 0; j < 6; j = j + 1) begin
                case (i)
                    0: x = 32'h7F800000;   // +Inf
                    1: x = 32'hFF800000;   // -Inf
                    2: x = 32'h7FC00000;   // +qNaN
                    3: x = 32'hFFC00001;   // -NaN, odd payload
                    4: x = 32'h00000000;   // +0
                    default: x = 32'h80000000;  // -0
                endcase
                case (j)
                    0: yv = 32'h7F800000;
                    1: yv = 32'hFF800000;
                    2: yv = 32'h7FC00000;
                    3: yv = 32'hFFC00001;
                    4: yv = 32'h00000000;
                    default: yv = 32'h80000000;
                endcase
                chk(x, yv);
                chk(x, 32'h3F800000);
                chk(x, 32'hC0490FDB);
            end
        $display("  specials matrix done (%0d fail so far)", fail_count);

        // ---- 6. random ------------------------------------------------------
        // Unfiltered 32-bit patterns, so Inf, NaN and subnormals all appear at
        // their natural rate rather than being excluded for convenience.
        for (i = 0; i < NRAND; i = i + 1) begin
            x  = $random(seed);
            yv = $random(seed);
            chk(x, yv);
        end
        // and a band-limited pass, where exponents are close enough that the
        // interesting arithmetic actually happens instead of one operand winning
        // outright. Unfiltered randoms are almost all "return the bigger one".
        for (i = 0; i < NRAND; i = i + 1) begin
            grp = $random(seed);
            et  = 8'd100 + (grp & 63);
            et2 = et + ((grp >> 8) & 7);
            ft  = $random(seed);
            ft2 = $random(seed);
            st  = ((grp >> 16) & 1) != 0;
            st2 = ((grp >> 17) & 1) != 0;
            x   = {st2, et,  ft};
            yv  = {st,  et2, ft2};
            chk(x, yv);
        end
        $display("  %0d random + %0d band-limited done", NRAND, NRAND);

        $display("=== %0d checks passed, %0d failed ===", pass_count, fail_count);
        if (fail_count != 0) $display("RESULT: FAIL");
        else                 $display("RESULT: PASS");
        $finish;
    end

    initial begin
        #200000000;
        $display("RESULT: FAIL (global timeout)");
        $finish;
    end
endmodule
