//=============================================================================
// tb_fx2fp32 -- leaf regression for rtl/fx2fp32.v.
//
// The X2 epilogue rounds ONCE per output element. That makes it the single point
// where the fixed-point accumulator's answer becomes an FP32 answer, so a bug here
// is a wrong bit in every one of the 256 results, in every instruction, and it
// would look exactly like an accumulator bug. Leaves before array -- the same
// order fp32_add and fp8_mul were built in.
//
//---------------------------------------------------- WHAT MAKES THIS A TEST
// The reference model is deliberately built the OTHER WAY ROUND from the DUT:
//
//   DUT: 6-level binary-search LZC -> shift LEFT to normalise -> take the top 24
//        bits -> round bit and sticky are fixed bit positions
//
//   ref: bit length from an explicit upward loop -> shift RIGHT by (bl-24) ->
//        round bit and sticky gathered by a loop over the discarded bits
//
// Two implementations that agree on 70k+ vectors is evidence. One implementation
// checked against a restatement of itself is not, and the LZC is exactly where
// that distinction matters: an off-by-one in the binary search and an off-by-one in
// the sticky range would cancel in a self-similar model.
//
// Three checks run on EVERY vector, not just the directed ones:
//   1. DUT == ref
//   2. sign symmetry:  f(-x, low) == f(x, low) ^ 0x8000_0000
//   3. scale invariance: f(x, low) == f(2x, low-1)   (when 2x still fits)
//
// (2) and (3) are properties of the specification that hold independently of
// either implementation, so they catch a bug the two models could share.
//
// Cross-language tie: 23 directed vectors generated by frac_to_fp32() in
// tb/fp8_golden.py, which is the same function the ACC=1 golden model rounds with.
// The generator asserts no two vectors give the same (acc, low) a different answer
// -- it caught a real contradiction where 1<<51 was treated as positive when in
// 52-bit two's complement it is negative.
//=============================================================================
`timescale 1ns/1ps

module tb_fx2fp32;

    parameter integer ACC_W = 52;
    parameter integer NRAND = 20000;

    reg  [ACC_W-1:0] acc;
    reg  signed [9:0] low;
    wire [31:0]      y;

    fx2fp32 #(.ACC_W(ACC_W)) dut (.acc(acc), .low(low), .y(y));

    // Width-typed rather than `integer`, because these get part-selected below and
    // part-selecting an `integer` is illegal in Verilog-2001 -- iverilog returns X
    // for any bit past 31 rather than erroring, which is worse. The first run of
    // this testbench reported 24,576 failures for exactly that reason.
    reg [31:0] checks = 32'd0;
    reg [31:0] errors = 32'd0;
    reg [31:0] cksum  = 32'd0;

    //-------------------------------------------------------------------------
    // Independent reference. Right-shift route, loop-based bit length.
    //-------------------------------------------------------------------------
    function [31:0] ref_fx2fp32;
        input [ACC_W-1:0] ab;
        input signed [9:0] lw;
        reg              s;
        reg [ACC_W-1:0]  mg;
        integer          bl, i, sh, eu, ef;
        reg [23:0]       sg, mf;
        reg              rb, sb;
        reg [24:0]       mr;
        reg [11:0]       eft;      // width-typed: part-selecting an `integer`
                                   // is illegal in Verilog-2001
        begin
            s  = ab[ACC_W-1];
            mg = s ? (~ab + {{(ACC_W-1){1'b0}}, 1'b1}) : ab;

            if (mg == {ACC_W{1'b0}}) begin
                ref_fx2fp32 = {s, 31'd0};
            end else begin
                // Bit length by an upward loop: bl = index of the highest set
                // bit, plus one. Structurally unlike the DUT's binary search.
                bl = 0;
                for (i = 0; i < ACC_W; i = i + 1)
                    if (mg[i]) bl = i + 1;

                eu = lw + bl - 1;             // MSB sits at (lw + bl - 1)

                if (bl > 24) begin
                    sh = bl - 24;
                    sg = mg >> sh;            // top 24 bits
                    rb = mg[sh-1];
                    sb = 1'b0;
                    for (i = 0; i < sh-1; i = i + 1)
                        if (mg[i]) sb = 1'b1;
                end else begin
                    sg = mg << (24 - bl);     // no bits discarded, exact
                    rb = 1'b0;
                    sb = 1'b0;
                end

                mr = {1'b0, sg} + ((rb && (sb || sg[0])) ? 25'd1 : 25'd0);
                if (mr[24]) begin mf = mr[24:1]; eu = eu + 1; end
                else        begin mf = mr[23:0];                end

                ef  = eu + 127;
                eft = ef;                 // plain assignment truncates; a
                                          // part-select on `integer` is illegal
                if      (ef >= 255) ref_fx2fp32 = {s, 8'hFF, 23'd0};
                else if (ef <= 0)   ref_fx2fp32 = {s, 31'd0};
                else                ref_fx2fp32 = {s, eft[7:0], mf[22:0]};
            end
        end
    endfunction

    //-------------------------------------------------------------------------
    // One vector: DUT vs ref, plus the two specification properties.
    //-------------------------------------------------------------------------
    reg [31:0] exp_y, got_y, sym_y, sc_y;
    reg [ACC_W-1:0] neg_a, dbl_a;

    task check;
        input [ACC_W-1:0] a_in;
        input signed [9:0] l_in;
        input [255:0] why;
        begin
            acc = a_in; low = l_in; #1;
            got_y = y;
            exp_y = ref_fx2fp32(a_in, l_in);
            checks = checks + 1;
            cksum  = cksum ^ (got_y + {24'd0, checks[7:0]});
            if (got_y !== exp_y) begin
                errors = errors + 1;
                $display("FAIL %0s: acc=%h low=%0d  dut=%h ref=%h",
                         why, a_in, l_in, got_y, exp_y);
            end

            // Property 2: sign symmetry. Skipped for zero (both signs of zero
            // are legal outputs and differ) and for -2^(ACC_W-1), which has no
            // representable positive counterpart.
            neg_a = ~a_in + {{(ACC_W-1){1'b0}}, 1'b1};
            if (a_in != {ACC_W{1'b0}} && a_in != {1'b1, {(ACC_W-1){1'b0}}}) begin
                acc = neg_a; #1;
                sym_y = y;
                checks = checks + 1;
                if (sym_y !== (got_y ^ 32'h8000_0000)) begin
                    errors = errors + 1;
                    $display("FAIL sign-sym %0s: acc=%h low=%0d  f(x)=%h f(-x)=%h",
                             why, a_in, l_in, got_y, sym_y);
                end
            end

            // Property 3: scale invariance, f(x,low) == f(2x,low-1). Only when
            // doubling does not overflow the width -- i.e. when the top two bits
            // of the magnitude agree, so the shifted value keeps its sign.
            dbl_a = a_in << 1;
            if ((a_in[ACC_W-1] === a_in[ACC_W-2]) && (l_in > -10'sd300)) begin
                acc = dbl_a; low = l_in - 10'sd1; #1;
                sc_y = y;
                checks = checks + 1;
                if (sc_y !== got_y) begin
                    errors = errors + 1;
                    $display("FAIL scale %0s: acc=%h low=%0d -> %h ; 2x,low-1 -> %h",
                             why, a_in, l_in, got_y, sc_y);
                end
            end
        end
    endtask

    // Directed vector with an externally supplied expectation, so a bug shared
    // by BOTH Verilog models still fails.
    task vec;
        input [ACC_W-1:0] a_in;
        input signed [9:0] l_in;
        input [31:0] want;
        begin
            acc = a_in; low = l_in; #1;
            checks = checks + 1;
            cksum  = cksum ^ (y + {24'd0, checks[7:0]});
            if (y !== want) begin
                errors = errors + 1;
                $display("FAIL python-vec: acc=%h low=%0d  dut=%h want=%h",
                         a_in, l_in, y, want);
            end
            // and it must also match the local reference
            if (y !== ref_fx2fp32(a_in, l_in)) begin
                errors = errors + 1;
                $display("FAIL python-vec ref disagrees: acc=%h low=%0d ref=%h",
                         a_in, l_in, ref_fx2fp32(a_in, l_in));
            end
        end
    endtask

    integer i, j, k, bl;
    reg [31:0] phase_base, err_base;
    reg [ACC_W-1:0] m, mm;
    reg [63:0] r64;
    reg signed [9:0] lo;
    reg kb;                       // k's low bit, width-typed for the same reason

    // phase 7: vectors from tb/fp8_golden.py's fx_to_fp32, the array's own oracle.
    // 112-bit words, acc[111:48] low[47:32] want[31:0].
    localparam integer NVEC = 6000;
    reg [111:0] vmem [0:NVEC-1];
    reg [63:0]  va64;
    reg [15:0]  vl16;
    reg [ACC_W-1:0] va;
    reg signed [9:0] vl;
    reg [31:0]  vw;

    // The `low` values used by the sweeps: 0, the design's actual range ends, and
    // a couple in between.
    localparam integer NLOW = 6;
    reg signed [9:0] lows [0:NLOW-1];

    initial begin
        if (ACC_W != 52) begin
            $display("NOTE: ACC_W=%0d -- the Python directed vectors are for 52 and are skipped",
                     ACC_W);
        end

        lows[0] =  10'sd0;
        lows[1] = -10'sd13;   // amx_fp8's highest `low`
        lows[2] = -10'sd44;   // typical
        lows[3] = -10'sd73;   // amx_fp8's lowest `low`
        lows[4] =  10'sd60;
        lows[5] = -10'sd126;  // just above FTZ for a 1-bit magnitude

        //==================== phase 1: Python directed vectors ================
        if (ACC_W == 52) begin
            // generated by tb/fp8_golden.py's frac_to_fp32 (ACC_W=52)
            vec(52'h0000000000000, 10'sd0    , 32'h00000000);  // zero -> +0
            vec(52'h0000000000001, 10'sd0    , 32'h3F800000);  // 1.0
            vec(52'hFFFFFFFFFFFFF, 10'sd0    , 32'hBF800000);  // -1.0
            vec(52'h0000000000003, 10'sd0    , 32'h40400000);  // 3.0
            vec(52'h0000001000000, 10'sd0    , 32'h4B800000);  // 2^24, last exact integer power
            vec(52'h0000001000001, 10'sd0    , 32'h4B800000);  // 2^24+1 -> RNE tie, to even
            vec(52'h0000001000003, 10'sd0    , 32'h4B800002);  // 2^24+3 -> rounds up
            vec(52'h0000002000001, 10'sd0    , 32'h4C000000);  // 2^25+1 -> below half, truncates
            vec(52'h0000002000003, 10'sd0    , 32'h4C000001);  // 2^25+3 -> RNE tie at the next binade
            vec(52'h7FFFFFFFFFFFF, 10'sd0    , 32'h59000000);  // max positive 2^51-1 -> rounds up to 2^51
            vec(52'h8000000000000, 10'sd0    , 32'hD9000000);  // -2^51: negating overflows in 52b, must still work
            vec(52'hFFFFFFEFFFFFF, 10'sd0    , 32'hCB800000);  // negative RNE tie
            vec(52'h0000000000001, -10'sd44  , 32'h29800000);  // deep LZC: 1 * 2^-44
            vec(52'h0000000000001, -10'sd73  , 32'h1B000000);  // lowest `low` amx_fp8 can produce
            vec(52'h7FFFFFFFFFFFF, -10'sd44  , 32'h43000000);  // full-width magnitude at the typical low
            vec(52'h0000000000001, 10'sd200  , 32'h7F800000);  // true overflow -> +Inf
            vec(52'hFFFFFFFFFFFFF, 10'sd200  , 32'hFF800000);  // true overflow -> -Inf
            vec(52'h8000000000000, 10'sd200  , 32'hFF800000);  // overflow, wide negative magnitude
            vec(52'h0000000000001, -10'sd200 , 32'h00000000);  // underflow -> FTZ +0
            vec(52'hFFFFFFFFFFFFF, -10'sd200 , 32'h80000000);  // underflow -> FTZ -0
            vec(52'h0000000000001, -10'sd127 , 32'h00000000);  // exactly the FTZ boundary (ef 0) -> flush
            vec(52'h0000000000001, -10'sd126 , 32'h00800000);  // one above it -> min normal, KEEP
            vec(52'h000000AAAAAAA, 10'sd0    , 32'h4D2AAAAB);  // alternating bits, sticky matters
            $display("phase 1 (python vectors)        : %0d checks, %0d errors",
                     checks, errors);
        end

        //==================== phase 2: exhaustive small magnitudes ============
        // 0..4095 at every `low`. This is the deep-LZC region -- 40 to 52 leading
        // zeros -- where the binary search's top levels all fire.
        phase_base = checks; err_base = errors;
        for (j = 0; j < NLOW; j = j + 1)
            for (i = 0; i < 4096; i = i + 1) begin
                mm = i;                       // NOT i[ACC_W-1:0]
                check(mm, lows[j], "small");
            end
        $display("phase 2 (exhaustive 0..4095)    : %0d checks, %0d errors",
                 checks - phase_base, errors - err_base);

        //==================== phase 3: every bit length =======================
        // For each possible MSB position: the power of two itself, one above it,
        // the all-ones value of that length, and two random patterns. This walks
        // the LZC through all ACC_W of its values with adversarial neighbours.
        phase_base = checks; err_base = errors;
        for (bl = 1; bl <= ACC_W; bl = bl + 1) begin
            for (j = 0; j < NLOW; j = j + 1) begin
                m = {{(ACC_W-1){1'b0}}, 1'b1} << (bl-1);
                check(m, lows[j], "pow2");
                check(m | {{(ACC_W-1){1'b0}}, 1'b1}, lows[j], "pow2+1");
                check(~({ACC_W{1'b1}} << bl), lows[j], "all-ones");
                for (k = 0; k < 2; k = k + 1) begin
                    r64 = {$random, $random};
                    m   = (r64[ACC_W-1:0] & ~({ACC_W{1'b1}} << bl))
                          | ({{(ACC_W-1){1'b0}}, 1'b1} << (bl-1));
                    check(m, lows[j], "randlen");
                end
            end
        end
        $display("phase 3 (all %0d bit lengths)     : %0d checks, %0d errors",
                 ACC_W, checks - phase_base, errors - err_base);

        //==================== phase 4: exact RNE ties =========================
        // A tie needs bl > 24: 24 significand bits, then a 1, then all zeros.
        // Built at both parities of the last significand bit, because ties-to-even
        // must round UP for odd and DOWN for even. This is the property that a
        // truncating rounder or a round-half-up rounder both get wrong.
        phase_base = checks; err_base = errors;
        for (bl = 25; bl <= ACC_W; bl = bl + 1) begin
            for (k = 0; k < 2; k = k + 1) begin
                // significand = 1000...0k  (24 bits, MSB set, LSB = k)
                kb = (k != 0);
                m = ({{(ACC_W-24){1'b0}}, 1'b1, 22'd0, kb} << (bl-24))
                    | ({{(ACC_W-1){1'b0}}, 1'b1} << (bl-25));
                check(m, 10'sd0,   "tie");
                check(m, -10'sd44, "tie");
                // one ULP-fraction above the tie: must round up regardless
                if (bl >= 26)
                    check(m | {{(ACC_W-1){1'b0}}, 1'b1}, 10'sd0, "tie+eps");
            end
        end
        $display("phase 4 (RNE ties both parities): %0d checks, %0d errors",
                 checks - phase_base, errors - err_base);

        //==================== phase 5: the two zero facts ======================
        // Pinned explicitly because a mutation replacing the zero branch with
        // {sgn,31'd0} SURVIVED the rest of this testbench -- correctly, since the
        // two are the same logic (mag==0 only when acc==0, and then sgn==0). These
        // checks turn that from a comment into an assertion, and also pin that -0
        // IS still reachable through FTZ, so a future "simplify" that drops sgn
        // from the underflow branch gets caught.
        phase_base = checks; err_base = errors;
        for (i = -512; i <= 511; i = i + 1) begin
            acc = {ACC_W{1'b0}}; low = i; #1;
            checks = checks + 1;
            if (y !== 32'h0000_0000) begin
                errors = errors + 1;
                $display("FAIL zero: acc=0 low=%0d gave %h, want 00000000", i, y);
            end
        end
        acc = {ACC_W{1'b1}}; low = -10'sd200; #1;      // -1 * 2^-200
        checks = checks + 1;
        if (y !== 32'h8000_0000) begin
            errors = errors + 1;
            $display("FAIL negzero: FTZ of a negative must give -0, got %h", y);
        end
        $display("phase 5 (zero / -0 facts)       : %0d checks, %0d errors",
                 checks - phase_base, errors - err_base);

        //==================== phase 6: random =================================
        phase_base = checks; err_base = errors;
        for (i = 0; i < NRAND; i = i + 1) begin
            r64 = {$random, $random};
            m   = r64[ACC_W-1:0];
            // Random shift right so the magnitude's bit length is uniform-ish
            // rather than always ~52.
            r64 = {$random, $random};
            m   = m >> (r64[5:0] % ACC_W);
            r64 = {$random, $random};
            lo  = $signed(r64[9:0]);
            check(m, lo, "rand");
        end
        $display("phase 6 (%0d random)         : %0d checks, %0d errors",
                 NRAND, checks - phase_base, errors - err_base);

        //============ phase 7: 6000 vectors from the ARRAY's own oracle =========
        // The 23 directed vectors above come from frac_to_fp32(). These come from
        // fx_to_fp32(), which is the function tb/fp8_golden.py actually uses to
        // produce the ACC=1 golden constants for tb_amx_fp8. If the RTL leaf and
        // that function disagree, every array-level golden is wrong and the array
        // testbench would blame the accumulator.
        //
        // The generator asserts fx_to_fp32 == frac_to_fp32 on all 6000 first, so
        // this is a three-way tie: two Python paths and the RTL.
        //
        // Regenerate with the command in tb/vec/README.
        phase_base = checks; err_base = errors;
        if (ACC_W != 52) begin
            $display("phase 7 (oracle vectors)        : skipped, file is for ACC_W=52");
        end else begin
            $readmemh("tb/vec/fx2fp32_w52.hex", vmem);
            if (vmem[0] === {112{1'bx}}) begin
                $display("phase 7 (oracle vectors)        : %sFILE MISSING%s -- tb/vec/fx2fp32_w52.hex",
                         "*** ", " ***");
                errors = errors + 1;      // a silently-skipped tie is not a tie
            end else begin
                for (i = 0; i < NVEC; i = i + 1) begin
                    if (vmem[i] !== {112{1'bx}}) begin
                        va64 = vmem[i][111:48];
                        vl16 = vmem[i][47:32];
                        vw   = vmem[i][31:0];
                        va   = va64[ACC_W-1:0];
                        vl   = vl16[9:0];         // low is in [-73,-13]: fits 10b
                        acc = va; low = vl; #1;
                        checks = checks + 1;
                        cksum  = cksum ^ (y + {24'd0, checks[7:0]});
                        if (y !== vw) begin
                            errors = errors + 1;
                            if (errors < 20)
                                $display("FAIL oracle[%0d]: acc=%h low=%0d  dut=%h want=%h",
                                         i, va, vl, y, vw);
                        end
                    end
                end
                $display("phase 7 (fp8_golden oracle)     : %0d checks, %0d errors",
                         checks - phase_base, errors - err_base);
            end
        end

        //==================== summary =========================================
        $display("");
        $display("========================================");
        $display("tb_fx2fp32  ACC_W=%0d", ACC_W);
        $display("  checks   : %0d", checks);
        $display("  errors   : %0d", errors);
        $display("  checksum : %08h", cksum);
        $display("========================================");
        // `RESULT: PASS` is the repo convention that the Makefile greps for -- see
        // tb_fp32_add.v:338 and tb_fp8_mul.v:257. The `*** PASSED ***` line is what
        // scripts/mutate.sh looks for. Both are printed so neither consumer breaks.
        if (errors != 0) begin
            $display("RESULT: FAIL");
            $display("*** FAILED ***");
            $fatal(1);
        end
        $display("RESULT: PASS");
        $display("*** PASSED ***");
        $finish;
    end

    // Global timeout. Without it a testbench that deadlocks reports nothing and
    // `grep -q 'RESULT: PASS'` fails with no explanation.
    initial begin
        #400000000;
        $display("RESULT: FAIL (global timeout)");
        $fatal(1);
    end
endmodule
